---
layout:     post
title:      Python学习笔记*
subtitle:   ......
date:       2022-6-23
author:     呆贝斯
header-img: img/post-bg-desk.jpg
catalog: true
tags:
    - Python
---

## Python简介
### 编译型语言和解释型语言
### Python的优缺点
### Python的应用领域
## 安装Python
### 普通安装
### 使用Anaconda
[Anaconda创建激活退出删除虚拟环境](https://blog.bookhub.com.cn/2022/04/20/Anaconda%E5%88%9B%E5%BB%BA%E6%BF%80%E6%B4%BB%E9%80%80%E5%87%BA%E5%88%A0%E9%99%A4%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83/)
## 运行一个Python程序
## Python基础知识
## Python的数据类型和变量
## Python程序的流程
## Python函数

## Python面向对象编程
### 面向对象编程概念
+ `面型对象`：是一种符合人类思维习惯的编程思想。客观世界中存在多种形态的事务，这些事物之间存在各种各样的联系。
在程序中使用对象来模拟现实中的事务，使用对象之间的关系来描述事物之间的联系，这种思想就是面对对象。
+ `对象`：一切事物皆为对象，将事物的属性和方法封装在一起，形成一个实体，这个实体就是对象。
+ `类`：具有相同属性和功能的对象的抽象。
+ `实例`：是一个真实的对象。比如我们都是”人“，所以你和我都是“人”类的实例。
+ `实例化`：创建对象的过程。

### 面向对象 VS 面向过程

## Python的错误、调试和测试
### 错误
#### 语法错误
语法错误就是解析代码时出现的错误。当代码不符合Python语法规则时，
Python解释器在解析时就会报SyntaxError语法错误，还会指出最早探测到错误的语句。
语法错误是解释器无法容忍的，必须全部纠正才能运行。
#### 运行错误
1. 

#### 异常处理 try except
1. 了解Python异常处理机制
2. try except else
3. try except finally
4. raise
    调试程序时看某些库的源代码，发现有如下代码读不懂，不理解后面这个from干什么用的。
    ```
    try:
    ...
    except KeyError:
        raise **Error('') from None
    
    try:
        ...
    except Exception as exc:
        raise **Error('') from exc
    ```
    先看普通写法，控制台会输出什么，结果如下。控制台输出了2个异常发生的位置和原因，同时在2个提示中间输出一句话“在处理上述异常时，又发生了另一个异常”。
    ```
    try:
        print(1/0)
    except Exception as exc:
        raise RuntimeError('程序执行过程中发生错误')
    
    Traceback (most recent call last):
      File "D:/*/tests.py", line 5, in <module>
        print(1/0)
    ZeroDivisionError: division by zero
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "D:/*/tests.py", line 7, in <module>
        raise RuntimeError('程序执行过程中发生错误')
    RuntimeError: 程序执行过程中发生错误
    ```
    再看raise **Error('') from exc写法，控制台输出了什么，结果如下。控制台输出了2个异常发生的位置和原因，同时在2个提示中间输出一句话“上述异常是下列异常的直接原因”。
    ```
    try:
        print(1/0)
    except Exception as exc:
        raise RuntimeError('程序执行过程中发生错误') from exc
    
    Traceback (most recent call last):
      File "D:/WorkSpace/backend/user/tests.py", line 5, in <module>
        print(1/0)
    ZeroDivisionError: division by zero
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "D:/WorkSpace/backend/user/tests.py", line 7, in <module>
        raise RuntimeError('程序执行过程中发生错误') from exc
    RuntimeError: 程序执行过程中发生错误
    ```
    最后看raise **Error('') from None写法，控制台输出了什么，结果如下。控制台只输出了我们写的抛出异常。
    ```
    try:
        print(1/0)
    except Exception as exc:
        raise RuntimeError('程序执行过程中发生错误') from None
    
    Traceback (most recent call last):
      File "D:/WorkSpace/backend/user/tests.py", line 7, in <module>
        raise RuntimeError('程序执行过程中发生错误') from None
    RuntimeError: 程序执行过程中发生错误
    ```
    总结：from 会为异常对象设置 __cause__ 属性表明异常的是由谁直接引起的。处理异常时发生了新的异常，
    在不使用 from 时更倾向于新异常与正在处理的异常没有关系。而 from 则是能指出新异常是因旧异常直接引起的。
    这样的异常之间的关联有助于后续对异常的分析和排查。from 语法会有个限制，就是第二个表达式必须是另一个异常类或实例。
    如果在异常处理程序或 finally 块中引发异常，默认情况下，
    异常机制会隐式工作会将先前的异常附加为新异常的 __context__属性。当然，
    也可以通过with_traceback()方法为异常设置上下文__context__属性，这也能在traceback更好的显示异常信息。
    from 还有个特别的用法：raise ... from None ，它通过设置 __suppress_context__ 属性指定来明确禁止异常关联。
    在异常处理程序或finally块中引发异常，可以通过from来指定异常因谁引起的。这些手段都是为了得到更友好的异常回溯信息，
    打印清晰的异常上下文。若要忽略上下文，则可以通过 raise ... from None 来禁止自动显示异常上下文。
5. sys.exec_info()获取异常信息
6. traceback模块获取异常信息

## Python的IO编程
## Python的线程、进程和协程
## Python的正则表达式
## Python常用内置模块
## Python常用第三方模块
## Python图形界面
## Python网络编程
## Python电子邮件
## Python访问数据库
## Python的Web开发
## 使用MicroPython
## 总结